
name: webapp-template

services:
  postgres:
    image: postgres:latest
    container_name: bookmark-postgres
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    networks:
      - net0
    volumes:
      - postgres:/var/lib/postgresql/data/

  client:
    build: ./client
    container_name: bookmark-client
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    networks:
      - net0
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  api:
    build: ./api
    container_name: bookmark-api
    environment:
      - API_PORT=$API_PORT
      - API_DEBUG_PORT=$API_DEBUG_PORT
      - DATABASE_URL=$POSTGRES_URL
    ports:
      - $API_PORT:$API_PORT
      - $API_DEBUG_PORT:$API_DEBUG_PORT
    depends_on:
      - postgres
    networks:
      - net0
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  ### Postgres admin ###
  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    environment:
      - POSTGRES_URL=$POSTGRES_URL
    ports:
      - $PRISMA_STUDIO_PORT:$PRISMA_STUDIO_PORT
    depends_on:
      - postgres
    networks:
      - net0

volumes:
  postgres:
  pgadmin:

networks:
  net0: {}
